/**
 * 추천 엔진 프로퍼티 테스트
 *
 * 추천 엔진 서비스의 핵심 동작에 대한 프로퍼티 기반 테스트를 정의한다.
 * - Property 7: 추천 결과 정렬 및 개수 제한
 * - Property 8: 코디 조합 구조 불변식
 * - Property 10: 추천 입력 검증
 * - Property 11: 추천 설명 제약
 */

import { describe, it, expect } from 'vitest';
import * as fc from 'fast-check';
import {
  generateOutfits,
  validateRecommendInput,
  generateExplanation,
  getItemsFromOutfit,
  type RecommendResult,
} from '@/services/recommend.service';
import type {
  ClothingItem,
  RecommendInput,
  OutfitRecommendation,
  OutfitCombination,
} from '@/types';
import { CATEGORIES, COLORS, SEASONS, STYLE_TAGS, OCCASIONS, WEATHERS } from '@/lib/constants';

// ─── 제너레이터 정의 ──────────────────────────────────────────────

/** 특정 카테고리의 ClothingItem 제너레이터 */
function clothingItemWithCategory(category: 'top' | 'bottom' | 'outer' | 'shoes') {
  return fc.record({
    id: fc.uuid(),
    imageUrl: fc.constant(null),
    category: fc.constant(category),
    color: fc.constantFrom(...COLORS),
    seasons: fc.subarray([...SEASONS], { minLength: 1 }),
    styleTags: fc.subarray([...STYLE_TAGS], { minLength: 1, maxLength: 4 }),
    memo: fc.constant(null),
    wearCount: fc.nat({ max: 50 }),
    createdAt: fc.date(),
    updatedAt: fc.date(),
  }) as fc.Arbitrary<ClothingItem>;
}

/** 조합 생성이 가능한 아이템 세트 제너레이터 (top + bottom + shoes 필수) */
const itemSetWithCombinationsArb = fc.tuple(
  fc.array(clothingItemWithCategory('top'), { minLength: 1, maxLength: 3 }),
  fc.array(clothingItemWithCategory('bottom'), { minLength: 1, maxLength: 3 }),
  fc.array(clothingItemWithCategory('shoes'), { minLength: 1, maxLength: 3 }),
  fc.array(clothingItemWithCategory('outer'), { minLength: 0, maxLength: 2 }),
).map(([tops, bottoms, shoes, outers]) => [...tops, ...bottoms, ...shoes, ...outers]);

/** 유효한 RecommendInput 제너레이터 */
const validRecommendInputArb = fc.record({
  occasion: fc.constantFrom(...OCCASIONS),
  weather: fc.constantFrom(...WEATHERS),
  preferredStyle: fc.constantFrom(...STYLE_TAGS),
}) as fc.Arbitrary<RecommendInput>;

/** 허용된 값 목록에 포함되지 않는 문자열 제너레이터 */
function invalidStringArb(allowedValues: readonly string[]) {
  return fc.string({ minLength: 1, maxLength: 20 }).filter(
    (s) => !(allowedValues as readonly string[]).includes(s)
  );
}

// ─── Property 7: 추천 결과 정렬 및 개수 제한 ──────────────────────────

// Feature: ai-closet-stylist, Property 7: 추천 결과 정렬 및 개수 제한
describe('Property 7: 추천 결과 정렬 및 개수 제한', () => {
  /**
   * **Validates: Requirements 4.1**
   *
   * For any valid recommendation input and any non-empty set of clothing items,
   * the recommendation engine should return at most 3 outfit combinations,
   * and they must be sorted in descending order by totalScore.
   */
  it('추천 결과는 최대 3개이며, totalScore 내림차순으로 정렬되어 있다', () => {
    fc.assert(
      fc.property(
        validRecommendInputArb,
        itemSetWithCombinationsArb,
        (input, items) => {
          const result: RecommendResult = generateOutfits(input, items);

          // 최대 3개 반환
          expect(result.recommendations.length).toBeLessThanOrEqual(3);

          // 결과가 2개 이상이면 내림차순 정렬 확인
          for (let i = 0; i < result.recommendations.length - 1; i++) {
            expect(result.recommendations[i].totalScore)
              .toBeGreaterThanOrEqual(result.recommendations[i + 1].totalScore);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('빈 아이템 세트일 때 추천 결과는 0개이며 안내 메시지가 있다', () => {
    fc.assert(
      fc.property(
        validRecommendInputArb,
        (input) => {
          const result = generateOutfits(input, []);

          expect(result.recommendations.length).toBe(0);
          expect(result.message).toBeDefined();
          expect(result.message!.length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ─── Property 8: 코디 조합 구조 불변식 ─────────────────────────────

// Feature: ai-closet-stylist, Property 8: 코디 조합 구조 불변식
describe('Property 8: 코디 조합 구조 불변식', () => {
  /**
   * **Validates: Requirements 4.3**
   *
   * For any outfit combination generated by the recommendation engine,
   * it must conform to exactly one of the three valid structures:
   * (top + bottom + shoes), (top + bottom + outer + shoes), or (dress + outer + shoes).
   */
  it('생성된 모든 코디 조합은 유효한 구조(top+bottom+shoes, top+bottom+outer+shoes, dress+outer+shoes) 중 하나이다', () => {
    fc.assert(
      fc.property(
        validRecommendInputArb,
        itemSetWithCombinationsArb,
        (input, items) => {
          const result: RecommendResult = generateOutfits(input, items);

          for (const rec of result.recommendations) {
            const outfit = rec.outfit;
            const isBasic = 'top' in outfit && 'bottom' in outfit && 'shoes' in outfit && !('outer' in outfit) && !('dress' in outfit);
            const isWithOuter = 'top' in outfit && 'bottom' in outfit && 'outer' in outfit && 'shoes' in outfit && !('dress' in outfit);
            const isDress = 'dress' in outfit && 'outer' in outfit && 'shoes' in outfit && !('top' in outfit) && !('bottom' in outfit);

            // 정확히 하나의 유효 구조와 일치
            const matchCount = [isBasic, isWithOuter, isDress].filter(Boolean).length;
            expect(matchCount).toBe(1);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('각 코디 조합의 아이템은 해당 역할의 카테고리와 일치한다', () => {
    fc.assert(
      fc.property(
        validRecommendInputArb,
        itemSetWithCombinationsArb,
        (input, items) => {
          const result: RecommendResult = generateOutfits(input, items);

          for (const rec of result.recommendations) {
            const outfit = rec.outfit;

            if ('dress' in outfit) {
              // dress + outer + shoes 구조
              expect(outfit.shoes.category).toBe('shoes');
              expect(outfit.outer.category).toBe('outer');
            } else if ('outer' in outfit) {
              // top + bottom + outer + shoes 구조
              expect(outfit.top.category).toBe('top');
              expect(outfit.bottom.category).toBe('bottom');
              expect(outfit.outer.category).toBe('outer');
              expect(outfit.shoes.category).toBe('shoes');
            } else {
              // top + bottom + shoes 구조
              expect(outfit.top.category).toBe('top');
              expect(outfit.bottom.category).toBe('bottom');
              expect(outfit.shoes.category).toBe('shoes');
            }
          }
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ─── Property 10: 추천 입력 검증 ───────────────────────────────────

// Feature: ai-closet-stylist, Property 10: 추천 입력 검증
describe('Property 10: 추천 입력 검증', () => {
  /**
   * **Validates: Requirements 4.6**
   *
   * For any string values provided as occasion, weather, or preferredStyle,
   * if any value is not in its respective allowed list, the recommendation engine
   * should return a validation error that includes the complete list of allowed
   * values for that field.
   */
  it('허용되지 않은 occasion 값은 허용 값 목록을 포함한 에러를 발생시킨다', () => {
    fc.assert(
      fc.property(
        invalidStringArb(OCCASIONS),
        fc.constantFrom(...WEATHERS),
        fc.constantFrom(...STYLE_TAGS),
        (invalidOccasion, weather, style) => {
          const input = {
            occasion: invalidOccasion,
            weather,
            preferredStyle: style,
          } as unknown as RecommendInput;

          expect(() => validateRecommendInput(input)).toThrow();
          try {
            validateRecommendInput(input);
          } catch (e: any) {
            // 에러 메시지에 허용된 occasion 목록이 포함되어야 함
            for (const allowed of OCCASIONS) {
              expect(e.message).toContain(allowed);
            }
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('허용되지 않은 weather 값은 허용 값 목록을 포함한 에러를 발생시킨다', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(...OCCASIONS),
        invalidStringArb(WEATHERS),
        fc.constantFrom(...STYLE_TAGS),
        (occasion, invalidWeather, style) => {
          const input = {
            occasion,
            weather: invalidWeather,
            preferredStyle: style,
          } as unknown as RecommendInput;

          expect(() => validateRecommendInput(input)).toThrow();
          try {
            validateRecommendInput(input);
          } catch (e: any) {
            // 에러 메시지에 허용된 weather 목록이 포함되어야 함
            for (const allowed of WEATHERS) {
              expect(e.message).toContain(allowed);
            }
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('허용되지 않은 preferredStyle 값은 허용 값 목록을 포함한 에러를 발생시킨다', () => {
    fc.assert(
      fc.property(
        fc.constantFrom(...OCCASIONS),
        fc.constantFrom(...WEATHERS),
        invalidStringArb(STYLE_TAGS),
        (occasion, weather, invalidStyle) => {
          const input = {
            occasion,
            weather,
            preferredStyle: invalidStyle,
          } as unknown as RecommendInput;

          expect(() => validateRecommendInput(input)).toThrow();
          try {
            validateRecommendInput(input);
          } catch (e: any) {
            // 에러 메시지에 허용된 style 목록이 포함되어야 함
            for (const allowed of STYLE_TAGS) {
              expect(e.message).toContain(allowed);
            }
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('유효한 입력값은 에러를 발생시키지 않는다', () => {
    fc.assert(
      fc.property(
        validRecommendInputArb,
        (input) => {
          expect(() => validateRecommendInput(input)).not.toThrow();
        }
      ),
      { numRuns: 100 }
    );
  });
});

// ─── Property 11: 추천 설명 제약 ───────────────────────────────────

// Feature: ai-closet-stylist, Property 11: 추천 설명 제약
describe('Property 11: 추천 설명 제약', () => {
  /**
   * **Validates: Requirements 4.2, 5.1, 5.2, 5.4**
   *
   * For any outfit combination with at least one attribute (color, season tag, or
   * occasion tag) present, the generated explanation must be at most 200 characters,
   * must contain at least one reason referencing an available attribute, and must
   * never be null or empty.
   * When all attributes are absent, a non-empty default explanation must be returned.
   */
  it('속성이 있는 조합의 설명은 200자 이내이고, 비어있지 않으며, 속성 관련 이유를 포함한다', () => {
    fc.assert(
      fc.property(
        validRecommendInputArb,
        itemSetWithCombinationsArb,
        (input, items) => {
          const result: RecommendResult = generateOutfits(input, items);

          for (const rec of result.recommendations) {
            const explanation = rec.explanation;

            // 설명은 null이거나 빈 문자열이 아니어야 함
            expect(explanation).not.toBeNull();
            expect(explanation).not.toBe('');
            expect(explanation.length).toBeGreaterThan(0);

            // 최대 200자 제한
            expect(explanation.length).toBeLessThanOrEqual(200);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('generateExplanation은 속성이 있을 때 200자 이내 비어있지 않은 설명을 반환한다', () => {
    // 최소 1개의 속성(색상, 계절, 스타일)이 있는 아이템으로 조합 생성
    const outfitWithAttributesArb = fc.tuple(
      clothingItemWithCategory('top'),
      clothingItemWithCategory('bottom'),
      clothingItemWithCategory('shoes'),
    ).map(([top, bottom, shoes]) => ({
      top,
      bottom,
      shoes,
    } as OutfitCombination));

    fc.assert(
      fc.property(
        outfitWithAttributesArb,
        validRecommendInputArb,
        (outfit, context) => {
          const explanation = generateExplanation(outfit, context);

          // 설명은 null이 아니고 빈 문자열이 아님
          expect(explanation).not.toBeNull();
          expect(explanation).not.toBe('');
          expect(explanation.length).toBeGreaterThan(0);

          // 최대 200자 제한
          expect(explanation.length).toBeLessThanOrEqual(200);

          // 아이템에 색상/계절/스타일 속성이 있으므로 설명에 이유가 포함됨
          const items = getItemsFromOutfit(outfit);
          const hasColor = items.some((item) => item.color);
          const hasSeason = items.some((item) => item.seasons.length > 0);
          const hasStyle = items.some((item) => item.styleTags.length > 0);

          // 속성이 하나라도 있으면 설명은 기본 설명이 아님
          if (hasColor || hasSeason || hasStyle) {
            expect(explanation.length).toBeGreaterThan(0);
          }
        }
      ),
      { numRuns: 100 }
    );
  });

  it('모든 속성이 부재할 때 기본 설명을 반환한다', () => {
    // 모든 속성이 비어있는 아이템으로 조합 생성
    const emptyAttributeItem = (category: 'top' | 'bottom' | 'shoes') => fc.record({
      id: fc.uuid(),
      imageUrl: fc.constant(null),
      category: fc.constant(category),
      color: fc.constant('' as any), // 빈 색상
      seasons: fc.constant([] as any), // 빈 계절
      styleTags: fc.constant([] as any), // 빈 스타일
      memo: fc.constant(null),
      wearCount: fc.constant(0),
      createdAt: fc.date(),
      updatedAt: fc.date(),
    }) as fc.Arbitrary<ClothingItem>;

    const emptyOutfitArb = fc.tuple(
      emptyAttributeItem('top'),
      emptyAttributeItem('bottom'),
      emptyAttributeItem('shoes'),
    ).map(([top, bottom, shoes]) => ({
      top,
      bottom,
      shoes,
    } as OutfitCombination));

    fc.assert(
      fc.property(
        emptyOutfitArb,
        validRecommendInputArb,
        (outfit, context) => {
          const explanation = generateExplanation(outfit, context);

          // 기본 설명은 비어있지 않아야 함
          expect(explanation).not.toBeNull();
          expect(explanation).not.toBe('');
          expect(explanation.length).toBeGreaterThan(0);

          // 최대 200자 제한
          expect(explanation.length).toBeLessThanOrEqual(200);
        }
      ),
      { numRuns: 100 }
    );
  });
});
